name: Deploy GitHub Pages Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

# Permissions for deploying to gh-pages branch
permissions:
  contents: write

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Documentation to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: "docs: deploy latest documentation & download portal [skip ci]"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
